name: Deploy Backend to Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code 
        uses: actions/checkout@v3

      # Step 2: Set up SSH
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 159.65.151.121 >> ~/.ssh/known_hosts
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

      # Step 3: Test SSH Connection
      - name: Test SSH Connection
        run: |
          ssh -o StrictHostKeyChecking=no root@159.65.151.121 "echo SSH Connection Successful"

      # Step 4: Deploy Code
      - name: Deploy Code
        run: |
          ssh root@159.65.151.121 << 'EOF'
            # Deployment steps
            cd /root || exit 1
            if [ -d "saveit-backend" ]; then
              mv saveit-backend old-saveit-backend || true
            fi
            mkdir saveit-backend
          EOF

      # Step 5: Upload Backend Files
      - name: Upload Files
        run: |
          scp -r ./ root@159.65.151.121:/root/saveit-backend

      # Step 6: Finalize Deployment
      - name: Finalize Deployment
        run: |
          ssh root@159.65.151.121 << 'EOF'
            cd /root/saveit-backend || exit 1
            npm install
            pm2 restart index || pm2 start index.js
          EOF
